config/routes.rb
Project3::Application.routes.draw do

    resources :sessions, :only => [:new, :create, :destroy]
    resources :users
    resources :bookmarks 
    resources :pages
       
    root 		    :to => 'sessions#new'
    
    #-----  Session routes -------------------#
    match '/signin',        :to => 'sessions#new'
    match '/signout',       :to => 'sessions#destroy'
    
    #-----  Users routes   -------------------#
    match '/index',         :to => 'users#index'
    match '/show',          :to => 'users#show'
    match '/signup', 	    :to => 'users#new'
    match '/edit',          :to => 'users#edit'
    match '/profile',       :to => "users#profile" 
    
    #-----  Pages routes ---------------------#
    match '/help',          :to => 'pages#help'
    match '/search',        :to => 'pages#search'
    match '/home',          :to => 'pages#home'
     
    #-----  Bookmarks routes ----------------#
    match '/show',          :to => 'bookmarks#show'
    match '/index',         :to => 'bookmarks#index'
  
end

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :integer         not null, primary key
#  url        :string(255)
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#
class Bookmark < ActiveRecord::Base
    
    attr_accessible :url, :name
    belongs_to :user
    
    validates :url, :presence => true,
                     :length => {:minimum => 10}
    
    validates :name, :presence => true,
                     :length => {:maximum => 100}
              
    validates :user_id, :presence => true
                     
    default_scope :order => "bookmarks.created_at DESC"
    
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_filter :authenticate
    before_filter :authorized_user, :only => :destroy
   
    # GET /bookmarks
    def index
        @bookmarks = Bookmark.all
    end
    ###
    #GET /bookmarks/1
    def show
        @bookmark = Bookmark.find(params[:id])
    end
    ###
    #GET /bookmarks/new
    def new
        @bookmark = Bookmark.new
        @title = "New Bookmark"
    end
    ####
    # GET /bookmarks/1/edit
    def edit
        @bookmark = Bookmark.find(params[:id])
    end
    ####
    # POST /bookmarks
     def create
        @bookmark = current_user.bookmars.build(params[:bookmark])
        if @bookmark.save
            redirect_to root_path, :flash => {:success => "Bookmark created!"}
        else
            @feed_items = []
            render 'users/show'
        end
    end
    
    # PUT /bookmark/1
    def update
        @bookmark = Bookmark.find(params[:id])
        respond_to do |format|
            if @bookmark.update_attributes(params[:bookmark])
                format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
                format.json { head :ok }
            else
                format.html { render action: "edit" }
                format.json { render json: @bookmark.errors, status: :unprocessable_entity }
            end
        end
    end
    ###
    # DELETE /bookmarks/1
    def destroy
         @bookmark.destroy
        redirect_to current_user, :flash => {:success => "Bookmark deleted!"}
    end
    ####
    private
        def authorized_user
            @bookmark = Bookmark.find(params[:id])
            redirect_to root_path unless current_user?(@bookmark.user)
        end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr>
    <td class="bookmark">
        <div class="content">
            URL : <a href="<%= bookmark.url %>" target=_blank ><%= bookmark.url %></a>
        </div>
        <div class="content">
            Name: <%= bookmark.name %>
        </div>
        <span class="timestamp">
           Posted <strong><i><%= time_ago_in_words(bookmark.created_at) %></i></strong> ago.
        </span>
    </td>
        <% user = bookmark.user rescue User.find(bookmark.user_id)%>
        <% if current_user?(user) %>
    <td>
            <%= link_to "delete", bookmark, :method => :delete,
                                                        :confirmation => "You sure",
                                                        :title => bookmark.name %>
    </td>
        <% end %>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %>
        prohibited this user from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>
<%= render 'form' %>

<%= link_to 'Show', @bookmark %>
<%= link_to 'Back', @bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Book<b><i>ma<b><i>rs Listing </h1>
<table>
  <tr>
    <th>Url</th>
    <th>Name</th>
    <th>User Id</th>
    <th></th>
    <th></th>
  </tr>

<% @bookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.url %></td>
    <td><%= bookmark.name %></td>
    <td><%= bookmark.user_id %></td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form'%>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Name:</b>
  <%= @bookmark.name %>
</p>

<p>
  <b>URL:</b>
  <%= @bookmark.url %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>