config/routes.rb
Project3::Application.routes.draw do

    resources :sessions, :only => [:new, :create, :destroy]
    resources :users
    resources :bookmarks 
    resources :pages
       
    root 		    :to => 'sessions#new'
    
    #-----  Session routes -------------------#
    match '/signin',        :to => 'sessions#new'
    match '/signout',       :to => 'sessions#destroy'
    
    #-----  Users routes   -------------------#
    match '/index',         :to => 'users#index'
    match '/show',          :to => 'users#show'
    match '/signup', 	    :to => 'users#new'
    match '/edit',          :to => 'users#edit'
    match '/profile',       :to => "users#profile" 
    
    #-----  Pages routes ---------------------#
    match '/help',          :to => 'pages#help'
    match '/search',        :to => 'pages#search'
    match '/home',          :to => 'pages#home'
     
    #-----  Bookmarks routes ----------------#
    match '/show',          :to => 'bookmarks#show'
    match '/index',         :to => 'bookmarks#index'
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Sign up", signup_path %></li>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Search",  search_path %></li>
    </ul>		
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo,  root_path %>
    <nav class="round links">
      <ul>
	<% if signed_in? %>
	     <%= render 'layouts/logged' %>
	<% else %>
	    <%= render 'layouts/non-logged' %>
	<% end %>
     </ul>
  </nav>
</header>

app/views/layouts/_logged.html.erb
<li><%= link_to "Profile",  profile_path, :method => :profile %></li>
<li><%= link_to "Users",    users_path %></li>
<li><%= link_to "Settings", edit_user_path(current_user) %></li>
<li><%= link_to "Logout",   signout_path, :method => :delete %> </li>
	

app/views/layouts/_non-logged.html.erb
<li><%= link_to "Sign in", signin_path %> |or| <%= link_to "Sign up", signup_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "Search", search_path %></li>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!Doctype html>
  <html>
    <head>
      <title><%= title %></title>
      <%= csrf_meta_tag %>
      <%= render 'layouts/stylesheets' %>
      <%= javascript_include_tag :defaults %>
    </head>
  <body>
    <div class="container">
      <header>
	<%= render 'layouts/header' %>
      </header>	
      <section class="round">
	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>">
	    <%= value %>
	  </div>
        <% end %>
	<%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  </html>